
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1003, 'Books');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1002, 'Amazon');
INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1001, 'SpiderMan', 1001, 1001, 10, current_timestamp);
INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY,  FK_SUPPLIER, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1002, 'Vox-Machine', 1002, 1002, 50, current_timestamp);
INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY,  FK_SUPPLIER, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1003, 'Lord of the rings', 1002, 1002, 30, current_timestamp);


